source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def required_pods

  pod 'library', :path => '../..//library'


end

target "Blue-Falcon" do
    required_pods
end
target "Blue-FalconTests" do
    required_pods
end
target "Blue-FalconUITests" do
    required_pods
end
